version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/prepare
      timeout: 10000
      runas: root
    - location: scripts/start_server
      timeout: 5000
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 5000
      runas: root
