version: 0.0
os: linux
files:
  - source: docker-compose-stage.yml
    destination: docker-compose.yml
hooks:
  BeforeInstall:
    - location: scripts/prepare.sh
      timeout: 10000
      runas: root
    - location: scripts/start_server.sh
      timeout: 5000
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 5000
      runas: root
