version: 0.0
os: linux
files:
  - source: docker-compose-stage.yml
    destination: docker-compose.yml
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 100000
      runas: root
  ApplicationStop:
    - location: scripts/app_start.sh
      timeout: 5000
      runas: root
  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 5000
      runas: root
