version: '2'
services:
  database:
    image: mongo:3.2
    container_name: QS_MONGO
    ports:
      - "28017:27017"

  api:
    image: simonzg/qs_api
    build:
      context: ./api/
      dockerfile: ./_docker/api/stage.Dockerfile
    container_name: QS_CORE
    environment:
      DB_HOST: "database"
      DB_PORT: 27017

  web:
    image: simonzg/qs_web
    build:
      context: ./web/
      dockerfile: ./stage.Dockerfile
    container_name: QS_WEB
    environment:
      API_HOST: "api.qs.prod"

  nginx:
    image: simonzg/qs_nginx
    build:
      context: ./api/
      dockerfile: ./_docker/nginx/stage.Dockerfile
    container_name: QS_NGINX
    ports:
      - "80:80"
