version: '3'
services:
  database:
    image: mongo:3.2
    container_name: QS_MONGO
    ports:
      - "28017:27017"

  api:
    image: simonzg/qs_api:stage
    container_name: QS_API
    environment:
      DB_HOST: "database"
      DB_PORT: 27017

  web:
    image: simonzg/qs_web:stage
    container_name: QS_WEB
    ports:
      - "80:80"
