version: '2'
services:
  database:
    image: mongo:3.2
    container_name: QS_MONGO
    ports:
      - "28017:27017"

  api:
    build:
      context: ./api/
      dockerfile: ./_docker/api/prod.Dockerfile
    container_name: QS_CORE
    environment:
      DB_HOST: "database"
      DB_PORT: 27017

  nginx:
    build:
      context: ./api/
      dockerfile: ./_docker/nginx/prod.Dockerfile
    container_name: QS_NGINX
    ports:
      - "80:80"

  web:
    build:
      context: ./web/
      dockerfile: ./prod.Dockerfile
    container_name: QS_WEB
    environment:
      API_HOST: "api.qs.prod"
