version: '2'
services:
  database:
    image: mongo:3.2
    container_name: QS_MONGO
    ports:
      - "28017:27017"

  api:
    container_name: QS_API
    build:
      context: .
      dockerfile: ./api.Dockerfile
    environment:
      DB_HOST: "database"
      DB_PORT: 27017

  web:
    image: simonzg/qs_web:stage
    container_name: QS_WEB
    ports:
      - "80:80"
